# Generated by Django 4.0.1 on 2022-07-24 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
    ]
