# Generated by Django 4.0.1 on 2022-07-24 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_patient_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='user',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='user',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='phone',
        ),
    ]
