# Generated by Django 4.0.1 on 2022-07-26 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_user_doctor_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('category', models.CharField(choices=[('mh', 'mental helath'), ('hd', 'heart disease'), ('ld', 'lungs disease'), ('fc', 'fracture')], max_length=3)),
                ('summary', models.TextField()),
                ('content', models.CharField(max_length=200)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.doctor')),
            ],
        ),
    ]
