# Generated by Django 4.0.6 on 2022-07-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_post_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Mental Health', 'mental helath'), ('Heart Disease', 'heart disease'), ('Lungs Disease', 'lungs disease'), ('Fracture', 'fracture')], max_length=30),
        ),
    ]
